package io.optionalfield.processor.jackson;

import java.lang.reflect.Field;
import io.optionalfield.processor.OptionalField;

import com.fasterxml.jackson.annotation.JsonProperty;
import tools.jackson.core.JacksonException;
import tools.jackson.core.JsonGenerator;
import tools.jackson.databind.SerializationContext;
import tools.jackson.databind.ValueSerializer;
import tools.jackson.databind.annotation.JsonSerialize;

/**
 * Base Jackson serializer for classes generated by {@code @OptionalClassReq}.
 *
 * <p>Only writes fields whose {@link io.optionalfield.processor.OptionalField#isPresent()} is
 * {@code true}, producing a minimal JSON patch document. Field names are taken from
 * {@code @JsonProperty} when present. Custom serializers declared via {@code @JsonSerialize(using=...)}
 * on the source field are instantiated and delegated to reflectively.
 *
 * <p>The generated {@code *Req} class provides a concrete subclass automatically. No methods
 * need to be overridden:
 *
 * <pre>{@code
 * public static class MySerializer extends AbstractOptionalFieldClassSerializer<MyReq> {}
 * }</pre>
 *
 * @param <T> the source class type
 */
public abstract class AbstractOptionalFieldClassSerializer<T> extends ValueSerializer<T> {
    @Override public void serialize(T value, JsonGenerator gen, SerializationContext ctxt) throws JacksonException {
        gen.writeStartObject();
        for (Field field : value.getClass().getDeclaredFields()) {
            field.setAccessible(true);
            try {
                String fieldName = field.getName();
                JsonProperty jsonProperty = field.getAnnotation(JsonProperty.class);
                if (jsonProperty != null && !jsonProperty.value().isEmpty()) {
                    fieldName = jsonProperty.value();
                }
                Object fieldValue = field.get(value);
                if (fieldValue instanceof OptionalField<?> optField) {
                    if (optField.isPresent()) {
                        gen.writeName(fieldName);
                        writeFieldValue(field, optField.getValue(), gen, ctxt);
                    }
                } else if (fieldValue != null) {
                    gen.writeName(fieldName);
                    writeFieldValue(field, fieldValue, gen, ctxt);
                }
            } catch (IllegalAccessException e) {
                throw new RuntimeException("Failed to access field: " + field.getName(), e);
            }
        }

        gen.writeEndObject();
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private void writeFieldValue(Field field, Object fieldValue, JsonGenerator gen, SerializationContext ctxt) throws JacksonException {
        JsonSerialize jsonSerialize = field.getAnnotation(JsonSerialize.class);
        if (jsonSerialize != null && jsonSerialize.using() != ValueSerializer.None.class) {
            try {
                ValueSerializer serializer = jsonSerialize.using().getDeclaredConstructor().newInstance();
                serializer.serialize(fieldValue, gen, ctxt);
            } catch (Exception e) {
                throw new RuntimeException("Failed to instantiate serializer from @JsonSerialize on field: " + field.getName(), e);
            }
        } else {
            gen.writePOJO(fieldValue);
        }
    }
}
