package com.gredok.optionalfield.processor.jackson;

import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import com.gredok.optionalfield.processor.OptionalField;

import com.fasterxml.jackson.annotation.JsonProperty;
import tools.jackson.core.JsonParser;
import tools.jackson.databind.DeserializationContext;
import tools.jackson.databind.DeserializationFeature;
import tools.jackson.databind.JavaType;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.ValueDeserializer;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.node.JsonNodeType;

/**
 * Base Jackson deserializer for classes generated by {@code @OptionalClassReq}.
 *
 * <p>Walks the JSON tree using reflection and sets each {@link com.gredok.optionalfield.processor.OptionalField}
 * on the target instance. A field is marked <em>present</em> when its key exists in the JSON object,
 * regardless of whether the value is {@code null}. The JSON key looked up for each field honors
 * {@code @JsonProperty}'s custom name, mirroring {@link AbstractOptionalFieldClassSerializer}. Unknown
 * JSON properties are reported through the standard {@code DeserializationContext.handleUnknownProperty}
 * mechanism (with an explicit fallback check), so {@code DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES}
 * is honored like any other Jackson deserializer.
 *
 * <p>The generated {@code *Req} class provides a concrete subclass automatically. You only need
 * to extend this directly when writing a hand-crafted equivalent:
 *
 * <pre>{@code
 * public static class MyDeserializer extends AbstractOptionalFieldClassDeserializer<MyReq> {
 *     @Override protected Class<MyReq> rawClass() { return MyReq.class; }
 * }
 * }</pre>
 *
 * @param <T> the target class type
 */
public abstract class AbstractOptionalFieldClassDeserializer<T> extends ValueDeserializer<T> {

    /**
     * Returns the raw {@link Class} of the type this deserializer targets.
     *
     * @return the target class; never {@code null}
     */
    protected abstract Class<T> rawClass();

    private static final ObjectMapper mapper = JsonMapper
            .builder()
            .build();

    @Override
    public T deserialize(JsonParser p, DeserializationContext ctxt) throws IllegalStateException {
        return useFields(p, ctxt, ctxt.readTree(p));
    }

    private T useFields(JsonParser p, DeserializationContext ctxt, JsonNode rootNode) {
        Class<T> rawClass = rawClass();
        T instance;
        try {
            instance = rawClass.getDeclaredConstructor().newInstance(); // Use default constructor if available
        } catch (Exception e) {
            throw new IllegalStateException("Error creating instance of " + rawClass.getName(), e);
        }

        List<Field> declaredFields = Arrays.stream(rawClass.getDeclaredFields())
                .filter(field -> !Modifier.isStatic(field.getModifiers())) // Skip static/constant fields
                .toList();

        if (rootNode.isObject()) {
            // Honor DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES (and any registered
            // DeserializationProblemHandlers) for JSON properties that don't map to a declared field.
            Set<String> knownJsonKeys = declaredFields.stream()
                    .map(AbstractOptionalFieldClassDeserializer::resolveJsonPropertyName)
                    .collect(Collectors.toSet());
            for (String propertyName : rootNode.propertyNames()) {
                if (!knownJsonKeys.contains(propertyName)) {
                    boolean handled = ctxt.handleUnknownProperty(p, this, instance, propertyName);
                    if (!handled && ctxt.isEnabled(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)) {
                        throw new IllegalStateException(
                                "Unrecognized field \"" + propertyName + "\" for class " + rawClass.getName());
                    }
                }
            }
        }

        declaredFields.forEach(field -> {
            field.setAccessible(true); // Make private fields accessible
            try {
                Object fieldValue = getObject(p, ctxt, field, rootNode); // Use getObject for field processing
                field.set(instance, fieldValue); // Set the field value on the instance
            } catch (Exception e) {
                throw new IllegalStateException("Error setting field value for " + field.getName(), e);
            }
        });
        return instance;
    }

    private Object getObject(JsonParser p, DeserializationContext ctxt, Field field, JsonNode rootNode) throws IOException {
        // The JSON key to look up, and the name carried on the OptionalField wrapper — honors
        // @JsonProperty's custom name, matching AbstractOptionalFieldClassSerializer.
        String jsonKey = resolveJsonPropertyName(field);
        JsonNode fieldNode = rootNode.has(jsonKey) ? rootNode.get(jsonKey) : null;

        boolean isPresent = fieldNode != null;
        Object fieldValue = null;

        if (isPresent && fieldNode.getNodeType() != JsonNodeType.NULL) {
            JavaType fieldType;

            // Build JavaType for the generic type of the field. This already carries full nested
            // generic structure (e.g. List<Dto>, List<List<Dto>>) — deserialize against it directly
            // rather than rebuilding a type from raw erased classes, which drops nested generics and
            // causes Jackson to fall back to LinkedHashMap for elements it can no longer type.
            if (isAssignableFrom(field.getGenericType(), OptionalField.class)) {
                fieldType = getJavaType(field.getGenericType());
            } else {
                fieldType = ctxt.getTypeFactory().constructType(field.getGenericType());
            }

            // Empty strings ("") are kept as-is, not coerced to null — for PATCH APIs these
            // commonly represent distinct updates.
            fieldValue = ctxt.readTreeAsValue(fieldNode, fieldType);
        }

        if (isAssignableFrom(field.getGenericType(), OptionalField.class)) {
            return new OptionalField<>(jsonKey, isPresent, fieldValue);
        }

        return fieldValue; // Return the deserialized field value
    }

    private static String resolveJsonPropertyName(Field field) {
        JsonProperty jsonProperty = field.getAnnotation(JsonProperty.class);
        if (jsonProperty != null && !jsonProperty.value().isEmpty()) {
            return jsonProperty.value();
        }
        return field.getName();
    }

    private static JavaType getJavaType(Type parameterType) {
        // Check if it's an Optional using isAssignableFrom
        if (isAssignableFrom(parameterType, OptionalField.class)) {
            if (parameterType instanceof ParameterizedType) {
                // Extract the generic type argument of Optional (e.g., String in Optional<String>)
                Type[] typeArguments = ((ParameterizedType) parameterType).getActualTypeArguments();
                if (typeArguments.length == 1) {
                    // Convert the inner type to JavaType
                    return mapper.getTypeFactory().constructType(typeArguments[0]);
                }
            }
        }
        throw new IllegalArgumentException("Parameter is not an Optional<T> with a valid generic type.");
    }

    private static boolean isAssignableFrom(Type type, Class<?> targetClass) {
        if (type instanceof ParameterizedType) {
            Type rawType = ((ParameterizedType) type).getRawType();
            if (rawType instanceof Class) {
                return targetClass.isAssignableFrom((Class<?>) rawType);
            }
        } else if (type instanceof Class) {
            return targetClass.isAssignableFrom((Class<?>) type);
        }
        return false;
    }
}
