/**
 * Java equivalent of demo/ObjectUpdater.kt — example utility showing how to consume the
 * OptionalField<T>-based *Req classes generated by optionalfield-processor.
 *
 * Copy this into your own project (adjust the package declaration) and use it to apply
 * PATCH-style partial updates from a generated *Req object onto an existing entity,
 * only touching fields that were actually present in the incoming request.
 *
 * Requires: com.gredok:optionalfield-processor on the classpath (for OptionalField).
 *
 * Note: Kotlin's version can check a target field's nullability via kotlin-reflect
 * (KProperty.returnType.isMarkedNullable) and reject nulling out a non-nullable property.
 * Plain Java has no equivalent runtime nullability metadata unless you add annotations
 * yourself (e.g. Jakarta Validation's @NotNull, or JSR-305 @Nonnull) and check for them
 * via reflection. This version approximates it by rejecting null for primitive fields
 * (int, boolean, etc., which can never hold null anyway) — adapt updateField() below if
 * you want to also honor a @NotNull annotation on entity fields.
 */
package com.example.util;

import com.gredok.optionalfield.processor.OptionalField;

import java.lang.reflect.Field;
import java.util.List;
import java.util.Objects;
import java.util.function.Function;

public final class ObjectUpdater {

    private ObjectUpdater() {
    }

    /**
     * Returns true if at least one of fieldsToCheck is present in updateRequest
     * and its value differs from the current value on entity.
     */
    public static <T, R> boolean isUpdated(T entity, R updateRequest, List<String> fieldsToCheck) {
        Class<?> entityClass = entity.getClass();
        Class<?> requestClass = updateRequest.getClass();

        for (String fieldName : fieldsToCheck) {
            try {
                Field requestField = requestClass.getDeclaredField(fieldName);
                requestField.setAccessible(true);
                Object fieldValue = requestField.get(updateRequest);

                if (fieldValue instanceof OptionalField<?> optionalField && optionalField.isPresent()) {
                    Field entityField = entityClass.getDeclaredField(fieldName);
                    entityField.setAccessible(true);
                    Object currentValue = entityField.get(entity);

                    if (!Objects.equals(currentValue, optionalField.getValue())) {
                        return true;
                    }
                }
            } catch (NoSuchFieldException | IllegalAccessException e) {
                // field not present on one side, or inaccessible — skip
            }
        }
        return false;
    }

    /**
     * Applies every present OptionalField from updateRequest onto entity.
     * Throws a plain RuntimeException if a primitive entity field would be set to null.
     */
    public static <T, R> T update(T entity, R updateRequest) {
        return update(entity, updateRequest, RuntimeException::new);
    }

    /**
     * Same as update(entity, updateRequest), but lets you supply a custom exception
     * factory (e.g. to throw your own validation/business exception type).
     */
    public static <T, R> T update(T entity, R updateRequest, Function<String, RuntimeException> exceptionFactory) {
        Class<?> entityClass = entity.getClass();
        Class<?> requestClass = updateRequest.getClass();

        for (Field requestField : requestClass.getDeclaredFields()) {
            requestField.setAccessible(true);
            try {
                Object fieldValue = requestField.get(updateRequest);
                if (fieldValue instanceof OptionalField<?> optionalField) {
                    if (optionalField.isPresent()) {
                        updateField(entity, entityClass, requestField.getName(), optionalField.getValue(), exceptionFactory);
                    }
                } else {
                    updateField(entity, entityClass, requestField.getName(), fieldValue, exceptionFactory);
                }
            } catch (IllegalAccessException e) {
                throw new IllegalStateException("Could not read field " + requestField.getName() + " on " + requestClass, e);
            }
        }
        return entity;
    }

    private static <T> void updateField(
            T entity,
            Class<?> entityClass,
            String fieldName,
            Object value,
            Function<String, RuntimeException> exceptionFactory
    ) {
        try {
            Field field = entityClass.getDeclaredField(fieldName);
            field.setAccessible(true);

            if (value == null && (field.getType() == boolean.class || field.getType() == Boolean.class)) {
                field.set(entity, false);
                return;
            }

            if (value == null && field.getType().isPrimitive()) {
                throw exceptionFactory.apply(fieldName + " cannot be null on class " + entityClass);
            }

            field.set(entity, value);
        } catch (NoSuchFieldException e) {
            // Field present on the *Req DTO but not on the entity — safe to ignore.
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("Could not set field " + fieldName + " on " + entityClass, e);
        }
    }
}
