/**
 * Example utility showing how to consume the `OptionalField<T>`-based `*Req` classes
 * generated by optionalfield-processor.
 *
 * Copy this into your own project (adjust the package declaration) and use it to apply
 * PATCH-style partial updates from a generated `*Req` object onto an existing entity,
 * only touching fields that were actually present in the incoming request.
 *
 * Requires: com.gredok:optionalfield-processor on the classpath (for OptionalField),
 * Kotlin reflection (kotlin-reflect) for the nullability check in updateField().
 */
package com.example.util

import com.gredok.optionalfield.processor.OptionalField
import kotlin.reflect.jvm.kotlinProperty

object ObjectUpdater {

    /**
     * Returns true if at least one of [fieldsToCheck] is present in [updateRequest]
     * and its value differs from the current value on [entity].
     */
    fun <T, R> isUpdated(entity: T, updateRequest: R, fieldsToCheck: List<String>): Boolean {
        val entityClass = entity!!::class.java
        val requestClass = updateRequest!!::class.java

        return fieldsToCheck.any { fieldName ->
            try {
                val requestField = requestClass.getDeclaredField(fieldName)
                requestField.isAccessible = true
                val fieldValue = requestField.get(updateRequest)

                if (fieldValue is OptionalField<*> && fieldValue.isPresent) {
                    val entityField = entityClass.getDeclaredField(fieldName)
                    entityField.isAccessible = true
                    val currentValue = entityField.get(entity)

                    currentValue != fieldValue.value
                } else {
                    false
                }
            } catch (e: NoSuchFieldException) {
                false
            }
        }
    }

    /**
     * Applies every present OptionalField from [updateRequest] onto [entity].
     * Throws a plain RuntimeException if a non-nullable entity field would be set to null.
     */
    fun <T, R> update(entity: T, updateRequest: R): T {
        return update(entity, updateRequest, { message -> RuntimeException(message) })
    }

    /**
     * Same as [update], but lets you supply a custom exception factory
     * (e.g. to throw your own validation/business exception type).
     */
    fun <T, R> update(entity: T, updateRequest: R, exception: (String) -> RuntimeException): T {
        val entityClass = entity!!::class.java
        val requestClass = updateRequest!!::class.java
        requestClass.declaredFields.forEach { requestField ->
            requestField.isAccessible = true
            val fieldValue = requestField.get(updateRequest)
            if (fieldValue is OptionalField<*>) {
                if (fieldValue.isPresent) {
                    updateField(entity, entityClass, requestField.name, fieldValue.value, exception)
                }
            } else {
                updateField(entity, entityClass, requestField.name, fieldValue, exception)
            }
        }
        return entity
    }

    private fun <T> updateField(
        entity: T,
        entityClass: Class<*>,
        fieldName: String,
        value: Any?,
        exception: (String) -> RuntimeException
    ) {
        try {
            val field = entityClass.getDeclaredField(fieldName)
            field.isAccessible = true
            if (value == null && field.type == Boolean::class.java) {
                field.set(entity, false)
                return
            }
            if (field.kotlinProperty?.returnType?.isMarkedNullable == false && value == null) {
                throw exception.invoke("$fieldName cannot be null on class $entityClass")
            }
            field.set(entity, value)
        } catch (e: NoSuchFieldException) {
            // Field present on the *Req DTO but not on the entity — safe to ignore.
        }
    }
}
